const playerData = [
  {
    playerName: "Marnus Labuschagne",
    sellingPrice: 9,
    basePrice: 0.5,
    country: "Australia",
    currentTeam: "rocktheking27@gmail.com",
    playerType: "Batter",
  },
  {
    playerName: "Adil Rashid",
    sellingPrice: 8.75,
    basePrice: 0.5,
    country: "England",
    currentTeam: "rocktheking27@gmail.com",
    playerType: "Bowler",
  },
  {
    playerName: "Devon Conway",
    sellingPrice: 14.75,
    basePrice: 0.5,
    country: "New Zealand",
    currentTeam: "rocktheking27@gmail.com",
    playerType: "Wicket-Keeper",
  },
  {
    playerName: "Marco Jansen",
    sellingPrice: 8.75,
    basePrice: 0.5,
    country: "South Africa",
    currentTeam: "rocktheking27@gmail.com",
    playerType: "All-Rounder",
  },
  {
    playerName: "Dimuth Karunaratne",
    sellingPrice: 3.4,
    basePrice: 0.5,
    country: "Sri Lanka",
    currentTeam: "rocktheking27@gmail.com",
    playerType: "Batter",
  },
  {
    playerName: "David Warner",
    sellingPrice: 16.75,
    basePrice: 0.5,
    country: "Australia",
    currentTeam: "rocktheking27@gmail.com",
    playerType: "Batter",
  },
  {
    playerName: "Usama Mir",
    sellingPrice: 0.5,
    basePrice: 0.5,
    country: "Pakistan",
    currentTeam: "rocktheking27@gmail.com",
    playerType: "Bowler",
  },
  {
    playerName: "Mohammad Nawaz",
    sellingPrice: 5,
    basePrice: 0.5,
    country: "Pakistan",
    currentTeam: "rocktheking27@gmail.com",
    playerType: "All-Rounder",
  },
  {
    playerName: "Tabraiz Shamsi",
    sellingPrice: 8,
    basePrice: 0.5,
    country: "South Africa",
    currentTeam: "rocktheking27@gmail.com",
    playerType: "Bowler",
  },
  {
    playerName: "Dilshan Madushanka",
    sellingPrice: 4,
    basePrice: 0.5,
    country: "Sri Lanka",
    currentTeam: "rocktheking27@gmail.com",
    playerType: "Bowler",
  },
  {
    playerName: "Sean Abbott",
    sellingPrice: 3,
    basePrice: 0.5,
    country: "Australia",
    currentTeam: "rocktheking27@gmail.com",
    playerType: "All-Rounder",
  },
  {
    playerName: "Tim Southee",
    sellingPrice: 8.1,
    basePrice: 0.5,
    country: "New Zealand",
    currentTeam: "rocktheking27@gmail.com",
    playerType: "Bowler",
  },
];

console.log(playerData);
