const playersData = [
  {
    playerName: "Ishan Kishan",
    sellingPrice: 3.2,
    basePrice: 0.5,
    country: "India",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Salman Ali Agha",
    sellingPrice: 0.5,
    basePrice: 0.5,
    country: "Pakistan",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Mohammad Siraj",
    sellingPrice: 12.75,
    basePrice: 0.5,
    country: "India",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Liam Livingstone",
    sellingPrice: 7.75,
    basePrice: 0.5,
    country: "England",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Charith Asalanka",
    sellingPrice: 3.6,
    basePrice: 0.5,
    country: "Sri Lanka",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Fakhar Zaman",
    sellingPrice: 8.25,
    basePrice: 0.5,
    country: "Pakistan",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Cameron Green",
    sellingPrice: 8.25,
    basePrice: 0.5,
    country: "Australia",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Trent Boult",
    sellingPrice: 16,
    basePrice: 0.5,
    country: "New Zealand",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Hardik Pandya",
    sellingPrice: 14.75,
    basePrice: 0.5,
    country: "India",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Mark Wood",
    sellingPrice: 6.75,
    basePrice: 0.5,
    country: "England",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Rachin Ravindra",
    sellingPrice: 4.2,
    basePrice: 0.5,
    country: "New Zealand",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Noor Ahmad",
    sellingPrice: 1.9,
    basePrice: 0.5,
    country: "Afghanistan",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Roelof van der Merwe",
    sellingPrice: 0.75,
    basePrice: 0.5,
    country: "Netherlands",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Josh Inglis",
    sellingPrice: 1,
    basePrice: 0.5,
    country: "Australia",
    currentTeam: "aashil556@gmail.com",
  },
  {
    playerName: "Aryan Dutt",
    sellingPrice: 0.35,
    basePrice: 0.5,
    country: "India",
    currentTeam: "aashil556@gmail.com",
  },
];
