const playersData = [
  {
    playerName: "Babar Azam",
    country: "Pakistan",
    currentTeam: "saladkardurvesh@gmail.com",
    sellingPrice: 14.25,
    basePrice: 0.5,
    playerType: "Batter",
  },
];

module.exports = playersData;

// {
//     playerName: "Iftikhar Ahmed",
//     country: "Pakistan",
//     currentTeam: "saladkardurvesh@gmail.com",
//     sellingPrice: 4.2,
//     basePrice: 0.5,
//     playerType: "All-Rounder",
//   },
//   {
//     playerName: "Alex Carey",
//     country: "Australia",
//     currentTeam: "saladkardurvesh@gmail.com",
//     sellingPrice: 6.25,
//     basePrice: 0.5,
//     playerType: "Wicket-Keeper",
//   },
//   {
//     playerName: "Sadeera Samarawickrama",
//     country: "Sri Lanka",
//     currentTeam: "saladkardurvesh@gmail.com",
//     sellingPrice: 3.2,
//     basePrice: 0.5,
//     playerType: "Wicket-Keeper",
//   },
//   {
//     playerName: "Aiden Markram",
//     country: "South Africa",
//     currentTeam: "saladkardurvesh@gmail.com",
//     sellingPrice: 13,
//     basePrice: 0.5,
//     playerType: "Batter",
//   },
//   {
//     playerName: "Josh Hazlewood",
//     country: "Australia",
//     currentTeam: "saladkardurvesh@gmail.com",
//     sellingPrice: 11.25,
//     basePrice: 0.5,
//     playerType: "Bowler",
//   },
//   {
//     playerName: "Keshav Maharaj",
//     country: "South Africa",
//     currentTeam: "saladkardurvesh@gmail.com",
//     sellingPrice: 5,
//     basePrice: 0.5,
//     playerType: "Bowler"
//   },
//   {
//     playerName: "Chris Woakes",
//     country: "England",
//     currentTeam: "saladkardurvesh@gmail.com",
//     sellingPrice: 10.25,
//     basePrice: 0.5,
//     playerType: "All-Rounder",
//   },
//   {
//     playerName: "Shreyas Iyer",
//     country: "India",
//     currentTeam: "saladkardurvesh@gmail.com",
//     sellingPrice: 9.25,
//     basePrice: 0.5,
//     playerType: "Batter",
//   },
//   {
//     playerName: "Ish Sodhi",
//     country: "New Zealand",
//     currentTeam: "saladkardurvesh@gmail.com",
//     sellingPrice: 8.25,
//     basePrice: 0.5,
//     playerType: "Bowler",
//   },
//   {
//     playerName: "Shadab Khan",
//     country: "Pakistan",
//     currentTeam: "saladkardurvesh@gmail.com",
//     sellingPrice: 4.2,
//     basePrice: 0.5,
//     playerType: "All-Rounder",
//   },
//   {
//     playerName: "Max O'Dowd",
//     country: "Netherlands",
//     currentTeam: "saladkardurvesh@gmail.com",
//     sellingPrice: 0.9,
//     basePrice: 0.5,
//     playerType: "All-Rounder",
//   },
